/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.jyc.cmpr_net_bd.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2023-02-02")
public class GetClusterResponse implements org.apache.thrift.TBase<GetClusterResponse, GetClusterResponse._Fields>, java.io.Serializable, Cloneable, Comparable<GetClusterResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("GetClusterResponse");

  private static final org.apache.thrift.protocol.TField CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("code", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CLUSTER_RESULT_FIELD_DESC = new org.apache.thrift.protocol.TField("clusterResult", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField REL_FIELD_DESC = new org.apache.thrift.protocol.TField("rel", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField MSG_FIELD_DESC = new org.apache.thrift.protocol.TField("msg", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new GetClusterResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new GetClusterResponseTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable String code; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<ClusterResultItem> clusterResult; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<RelItem> rel; // required
  public @org.apache.thrift.annotation.Nullable String msg; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CODE((short)1, "code"),
    CLUSTER_RESULT((short)2, "clusterResult"),
    REL((short)3, "rel"),
    MSG((short)4, "msg");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CODE
          return CODE;
        case 2: // CLUSTER_RESULT
          return CLUSTER_RESULT;
        case 3: // REL
          return REL;
        case 4: // MSG
          return MSG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.MSG};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CODE, new org.apache.thrift.meta_data.FieldMetaData("code", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CLUSTER_RESULT, new org.apache.thrift.meta_data.FieldMetaData("clusterResult", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ClusterResultItem.class))));
    tmpMap.put(_Fields.REL, new org.apache.thrift.meta_data.FieldMetaData("rel", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RelItem.class))));
    tmpMap.put(_Fields.MSG, new org.apache.thrift.meta_data.FieldMetaData("msg", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(GetClusterResponse.class, metaDataMap);
  }

  public GetClusterResponse() {
  }

  public GetClusterResponse(
    String code,
    java.util.List<ClusterResultItem> clusterResult,
    java.util.List<RelItem> rel)
  {
    this();
    this.code = code;
    this.clusterResult = clusterResult;
    this.rel = rel;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public GetClusterResponse(GetClusterResponse other) {
    if (other.isSetCode()) {
      this.code = other.code;
    }
    if (other.isSetClusterResult()) {
      java.util.List<ClusterResultItem> __this__clusterResult = new java.util.ArrayList<ClusterResultItem>(other.clusterResult.size());
      for (ClusterResultItem other_element : other.clusterResult) {
        __this__clusterResult.add(new ClusterResultItem(other_element));
      }
      this.clusterResult = __this__clusterResult;
    }
    if (other.isSetRel()) {
      java.util.List<RelItem> __this__rel = new java.util.ArrayList<RelItem>(other.rel.size());
      for (RelItem other_element : other.rel) {
        __this__rel.add(new RelItem(other_element));
      }
      this.rel = __this__rel;
    }
    if (other.isSetMsg()) {
      this.msg = other.msg;
    }
  }

  public GetClusterResponse deepCopy() {
    return new GetClusterResponse(this);
  }

  @Override
  public void clear() {
    this.code = null;
    this.clusterResult = null;
    this.rel = null;
    this.msg = null;
  }

  @org.apache.thrift.annotation.Nullable
  public String getCode() {
    return this.code;
  }

  public GetClusterResponse setCode(@org.apache.thrift.annotation.Nullable String code) {
    this.code = code;
    return this;
  }

  public void unsetCode() {
    this.code = null;
  }

  /** Returns true if field code is set (has been assigned a value) and false otherwise */
  public boolean isSetCode() {
    return this.code != null;
  }

  public void setCodeIsSet(boolean value) {
    if (!value) {
      this.code = null;
    }
  }

  public int getClusterResultSize() {
    return (this.clusterResult == null) ? 0 : this.clusterResult.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<ClusterResultItem> getClusterResultIterator() {
    return (this.clusterResult == null) ? null : this.clusterResult.iterator();
  }

  public void addToClusterResult(ClusterResultItem elem) {
    if (this.clusterResult == null) {
      this.clusterResult = new java.util.ArrayList<ClusterResultItem>();
    }
    this.clusterResult.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<ClusterResultItem> getClusterResult() {
    return this.clusterResult;
  }

  public GetClusterResponse setClusterResult(@org.apache.thrift.annotation.Nullable java.util.List<ClusterResultItem> clusterResult) {
    this.clusterResult = clusterResult;
    return this;
  }

  public void unsetClusterResult() {
    this.clusterResult = null;
  }

  /** Returns true if field clusterResult is set (has been assigned a value) and false otherwise */
  public boolean isSetClusterResult() {
    return this.clusterResult != null;
  }

  public void setClusterResultIsSet(boolean value) {
    if (!value) {
      this.clusterResult = null;
    }
  }

  public int getRelSize() {
    return (this.rel == null) ? 0 : this.rel.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<RelItem> getRelIterator() {
    return (this.rel == null) ? null : this.rel.iterator();
  }

  public void addToRel(RelItem elem) {
    if (this.rel == null) {
      this.rel = new java.util.ArrayList<RelItem>();
    }
    this.rel.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<RelItem> getRel() {
    return this.rel;
  }

  public GetClusterResponse setRel(@org.apache.thrift.annotation.Nullable java.util.List<RelItem> rel) {
    this.rel = rel;
    return this;
  }

  public void unsetRel() {
    this.rel = null;
  }

  /** Returns true if field rel is set (has been assigned a value) and false otherwise */
  public boolean isSetRel() {
    return this.rel != null;
  }

  public void setRelIsSet(boolean value) {
    if (!value) {
      this.rel = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public String getMsg() {
    return this.msg;
  }

  public GetClusterResponse setMsg(@org.apache.thrift.annotation.Nullable String msg) {
    this.msg = msg;
    return this;
  }

  public void unsetMsg() {
    this.msg = null;
  }

  /** Returns true if field msg is set (has been assigned a value) and false otherwise */
  public boolean isSetMsg() {
    return this.msg != null;
  }

  public void setMsgIsSet(boolean value) {
    if (!value) {
      this.msg = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case CODE:
      if (value == null) {
        unsetCode();
      } else {
        setCode((String)value);
      }
      break;

    case CLUSTER_RESULT:
      if (value == null) {
        unsetClusterResult();
      } else {
        setClusterResult((java.util.List<ClusterResultItem>)value);
      }
      break;

    case REL:
      if (value == null) {
        unsetRel();
      } else {
        setRel((java.util.List<RelItem>)value);
      }
      break;

    case MSG:
      if (value == null) {
        unsetMsg();
      } else {
        setMsg((String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CODE:
      return getCode();

    case CLUSTER_RESULT:
      return getClusterResult();

    case REL:
      return getRel();

    case MSG:
      return getMsg();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CODE:
      return isSetCode();
    case CLUSTER_RESULT:
      return isSetClusterResult();
    case REL:
      return isSetRel();
    case MSG:
      return isSetMsg();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that instanceof GetClusterResponse)
      return this.equals((GetClusterResponse)that);
    return false;
  }

  public boolean equals(GetClusterResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_code = true && this.isSetCode();
    boolean that_present_code = true && that.isSetCode();
    if (this_present_code || that_present_code) {
      if (!(this_present_code && that_present_code))
        return false;
      if (!this.code.equals(that.code))
        return false;
    }

    boolean this_present_clusterResult = true && this.isSetClusterResult();
    boolean that_present_clusterResult = true && that.isSetClusterResult();
    if (this_present_clusterResult || that_present_clusterResult) {
      if (!(this_present_clusterResult && that_present_clusterResult))
        return false;
      if (!this.clusterResult.equals(that.clusterResult))
        return false;
    }

    boolean this_present_rel = true && this.isSetRel();
    boolean that_present_rel = true && that.isSetRel();
    if (this_present_rel || that_present_rel) {
      if (!(this_present_rel && that_present_rel))
        return false;
      if (!this.rel.equals(that.rel))
        return false;
    }

    boolean this_present_msg = true && this.isSetMsg();
    boolean that_present_msg = true && that.isSetMsg();
    if (this_present_msg || that_present_msg) {
      if (!(this_present_msg && that_present_msg))
        return false;
      if (!this.msg.equals(that.msg))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCode()) ? 131071 : 524287);
    if (isSetCode())
      hashCode = hashCode * 8191 + code.hashCode();

    hashCode = hashCode * 8191 + ((isSetClusterResult()) ? 131071 : 524287);
    if (isSetClusterResult())
      hashCode = hashCode * 8191 + clusterResult.hashCode();

    hashCode = hashCode * 8191 + ((isSetRel()) ? 131071 : 524287);
    if (isSetRel())
      hashCode = hashCode * 8191 + rel.hashCode();

    hashCode = hashCode * 8191 + ((isSetMsg()) ? 131071 : 524287);
    if (isSetMsg())
      hashCode = hashCode * 8191 + msg.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(GetClusterResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.compare(isSetCode(), other.isSetCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.code, other.code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetClusterResult(), other.isSetClusterResult());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClusterResult()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clusterResult, other.clusterResult);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetRel(), other.isSetRel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rel, other.rel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetMsg(), other.isSetMsg());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMsg()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.msg, other.msg);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("GetClusterResponse(");
    boolean first = true;

    sb.append("code:");
    if (this.code == null) {
      sb.append("null");
    } else {
      sb.append(this.code);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("clusterResult:");
    if (this.clusterResult == null) {
      sb.append("null");
    } else {
      sb.append(this.clusterResult);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("rel:");
    if (this.rel == null) {
      sb.append("null");
    } else {
      sb.append(this.rel);
    }
    first = false;
    if (isSetMsg()) {
      if (!first) sb.append(", ");
      sb.append("msg:");
      if (this.msg == null) {
        sb.append("null");
      } else {
        sb.append(this.msg);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class GetClusterResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public GetClusterResponseStandardScheme getScheme() {
      return new GetClusterResponseStandardScheme();
    }
  }

  private static class GetClusterResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<GetClusterResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, GetClusterResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.code = iprot.readString();
              struct.setCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CLUSTER_RESULT
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list48 = iprot.readListBegin();
                struct.clusterResult = new java.util.ArrayList<ClusterResultItem>(_list48.size);
                @org.apache.thrift.annotation.Nullable ClusterResultItem _elem49;
                for (int _i50 = 0; _i50 < _list48.size; ++_i50)
                {
                  _elem49 = new ClusterResultItem();
                  _elem49.read(iprot);
                  struct.clusterResult.add(_elem49);
                }
                iprot.readListEnd();
              }
              struct.setClusterResultIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // REL
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list51 = iprot.readListBegin();
                struct.rel = new java.util.ArrayList<RelItem>(_list51.size);
                @org.apache.thrift.annotation.Nullable RelItem _elem52;
                for (int _i53 = 0; _i53 < _list51.size; ++_i53)
                {
                  _elem52 = new RelItem();
                  _elem52.read(iprot);
                  struct.rel.add(_elem52);
                }
                iprot.readListEnd();
              }
              struct.setRelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // MSG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.msg = iprot.readString();
              struct.setMsgIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, GetClusterResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.code != null) {
        oprot.writeFieldBegin(CODE_FIELD_DESC);
        oprot.writeString(struct.code);
        oprot.writeFieldEnd();
      }
      if (struct.clusterResult != null) {
        oprot.writeFieldBegin(CLUSTER_RESULT_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.clusterResult.size()));
          for (ClusterResultItem _iter54 : struct.clusterResult)
          {
            _iter54.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.rel != null) {
        oprot.writeFieldBegin(REL_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.rel.size()));
          for (RelItem _iter55 : struct.rel)
          {
            _iter55.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.msg != null) {
        if (struct.isSetMsg()) {
          oprot.writeFieldBegin(MSG_FIELD_DESC);
          oprot.writeString(struct.msg);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class GetClusterResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public GetClusterResponseTupleScheme getScheme() {
      return new GetClusterResponseTupleScheme();
    }
  }

  private static class GetClusterResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<GetClusterResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, GetClusterResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCode()) {
        optionals.set(0);
      }
      if (struct.isSetClusterResult()) {
        optionals.set(1);
      }
      if (struct.isSetRel()) {
        optionals.set(2);
      }
      if (struct.isSetMsg()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetCode()) {
        oprot.writeString(struct.code);
      }
      if (struct.isSetClusterResult()) {
        {
          oprot.writeI32(struct.clusterResult.size());
          for (ClusterResultItem _iter56 : struct.clusterResult)
          {
            _iter56.write(oprot);
          }
        }
      }
      if (struct.isSetRel()) {
        {
          oprot.writeI32(struct.rel.size());
          for (RelItem _iter57 : struct.rel)
          {
            _iter57.write(oprot);
          }
        }
      }
      if (struct.isSetMsg()) {
        oprot.writeString(struct.msg);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, GetClusterResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.code = iprot.readString();
        struct.setCodeIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list58 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.clusterResult = new java.util.ArrayList<ClusterResultItem>(_list58.size);
          @org.apache.thrift.annotation.Nullable ClusterResultItem _elem59;
          for (int _i60 = 0; _i60 < _list58.size; ++_i60)
          {
            _elem59 = new ClusterResultItem();
            _elem59.read(iprot);
            struct.clusterResult.add(_elem59);
          }
        }
        struct.setClusterResultIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list61 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.rel = new java.util.ArrayList<RelItem>(_list61.size);
          @org.apache.thrift.annotation.Nullable RelItem _elem62;
          for (int _i63 = 0; _i63 < _list61.size; ++_i63)
          {
            _elem62 = new RelItem();
            _elem62.read(iprot);
            struct.rel.add(_elem62);
          }
        }
        struct.setRelIsSet(true);
      }
      if (incoming.get(3)) {
        struct.msg = iprot.readString();
        struct.setMsgIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

