spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cmpr_net
    username: root
    password: 121342
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

thrift:
  port: 3003
  host: 127.0.0.1
  minWorkerThreads: 1
  maxWorkerThreads: 2